FROM mcr.microsoft.com/windows/server:ltsc2022
WORKDIR "/Program Files (x86)/Origin Games/Titanfall2"

COPY ./__Installer ./__Installer
ADD https://aka.ms/vs/17/release/vc_redist.x64.exe vc_redist.x64.exe 
RUN start /w vc_redist.x64.exe /install /quiet /norestart
RUN del vc_redist.x64.exe
ADD https://aka.ms/vs/17/release/vc_redist.x86.exe vc_redist.x86.exe 
RUN start /w vc_redist.x86.exe /install /quiet /norestart 
RUN del vc_redist.x86.exe
ADD https://download.microsoft.com/download/1/6/B/16B06F60-3B20-4FF2-B699-5E9B7962F9AE/VSU_4/vcredist_x64.exe vc_redist.x64.exe 
RUN start /w vc_redist.x64.exe /install /quiet /norestart 
RUN del vc_redist.x64.exe
ADD https://download.microsoft.com/download/1/6/B/16B06F60-3B20-4FF2-B699-5E9B7962F9AE/VSU_4/vcredist_x86.exe vc_redist.x86.exe 
RUN start /w vc_redist.x86.exe /install /quiet /norestart 
RUN del vc_redist.x86.exe
RUN powershell Start-Process -FilePath ".\__Installer\directx\redist\DXSETUP.exe" -ArgumentList "/Silent" -Wait
RUN start /w .\__Installer\vc\vc2010sp1\redist\vcredist_x64.exe /install /quiet /norestart
RUN start /w .\__Installer\vc\vc2012Update4\redist\vcredist_x64.exe /install /quiet /norestart
RUN powershell Set-ExecutionPolicy Unrestricted

ENTRYPOINT [ "NorthstarLauncher.exe" ]

#make sure to mount the game folder to /Program Files (x86)/Origin Games/Titanfall2